sensor_msgs/Image image
string negative_prompts
string positive_prompts
string prompt_engineering
float32 safety_threshold
int8 blur_kernel_size
float32 dynamic_threshold
---
sensor_msgs/Image heatmap
float32 curr_threshold
bool success